### ISSUE TITLE
Error: Sequelize, DB 관련 에러가 나옵니다. 

### ISSUE THREAD

**Issue by kwakseungmin23** [PLMOW/Pinterest-BE#14]
![image](https://user-images.githubusercontent.com/63998542/222953451-0e1770fe-34c3-49ab-9d2d-715ee79195cc.png)

C:\Users\User\Desktop\clonecoding\node_modules\sequelize\lib\sequelize.js:136
      throw new Error("Dialect needs to be explicitly supplied as of v4.0.0");
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (C:\Users\User\Desktop\clonecoding\node_modules\sequelize\lib\sequelize.js:136:13)
    at Object.<anonymous> (C:\Users\User\Desktop\clonecoding\db\models\index.js:15:15)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\User\Desktop\clonecoding\src\routes\index.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    
확인 부탁드리겠습니다. 
@minenam

**Comment by kwakseungmin23** [comment]
Solve with making dot env file
